#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <openssl/sha.h>

using namespace std;

// Function to compute SHA-1 hash
string sha1(const string &input) {
    unsigned char hash[SHA_DIGEST_LENGTH]; // SHA-1 produces 20 bytes
    SHA1((unsigned char*)input.c_str(), input.size(), hash);

    // Convert hash bytes to hex string
    stringstream ss;
    for (int i = 0; i < SHA_DIGEST_LENGTH; i++) {
        ss << hex << setw(2) << setfill('0') << (int)hash[i];
    }

    string result = ss.str();

    // Padding to 40 characters if needed (same as Java)
    while (result.length() < 40) {
        result = "0" + result;
    }

    return result;
}

int main() {
    cout << "HashCode Generated by SHA-1 Algorithm:\n\n";

    cout << "Enter text to hash: ";
    string input;
    getline(cin, input);

    cout << "\nInput: " << input << endl;
    cout << "SHA-1 Hash: " << sha1(input) << endl;

    return 0;
}
