#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <openssl/sha.h>

using namespace std;

// Function to compute SHA-256 hash
string sha256(const string &input) {
    unsigned char hash[SHA256_DIGEST_LENGTH];
    SHA256((unsigned char*)input.c_str(), input.size(), hash);

    // Convert to hexadecimal string
    stringstream ss;
    for (int i = 0; i < SHA256_DIGEST_LENGTH; i++) {
        ss << hex << setw(2) << setfill('0') << (int)hash[i];
    }
    return ss.str();
}

int main() {
    cout << "HashCode Generated by SHA-256 Algorithm:\n\n";

    cout << "Enter text to hash: ";
    string input;
    getline(cin, input);

    cout << "\nInput: " << input << endl;
    cout << "SHA-256 Hash: " << sha256(input) << endl;

    return 0;
}
